logbook:
    obfuscate:
        headers:
            - Cookie
            - Set-Cookie

logging:
    file:
        name: pupperfield.log
    level:
        org:
            zalando:
                logbook:
                    Logbook: trace
    logback:
        rollingpolicy:
            max-history: 31

server:
    compression:
        enabled: true
        min-response-size: 1024
    error:
        include-exception: false
        include-message: never
        include-path: never
        include-stacktrace: never
        whitelabel:
            enabled: false
    forward-headers-strategy: native
    http2:
        enabled: true
    port: 8080

spring:
    application:
        name: pupperfield
    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
    main:
        banner-mode: off
        keep-alive: true
    threads:
        virtual:
            enabled: true

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        supportedSubmitMethods: []
        tryItOutEnabled: false
